### ISSUE TITLE
fork fail kill all childs

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#102]
if we are running out of PIDS and do something like

cat | cat | cat | cat | ls

cat | cat | cat will run and the rest runs out 
prompt comes back but cats are not killed properly

testing: docker with arguments

**Comment by Chr-ss** [comment]
![Uploading IMG_20240729_140726.jpg…]()

**Comment by Chr-ss** [comment]
![IMG_20240729_140726](https://github.com/user-attachments/assets/595c4d13-c041-46bd-8448-b64912e744d3)

**Comment by sairutra** [comment]
docker run -it --pids-limit 5 --rm debian /bin/bash

**Comment by sairutra** [comment]
docker ps
CONTAINER ID   IMAGE     COMMAND       CREATED         STATUS        PORTS     NAMES
87b2e369f241   debian    "/bin/bash"   3 seconds ago   Up 1 second             laughing_bouman
docker cp minishell 87b2e369f241:/minishell

**Comment by sairutra** [comment]
apt update

**Comment by sairutra** [comment]
fixed in [09f1506](https://github.com/Chr-ss/minishell/pull/104/commits/09f1506046987d42101eb85351a60146bff3e7c2)
