### ISSUE TITLE
Return value on signals

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#107]
Sleep 10
Ctrl + C
echo $?

**Comment by Chr-ss** [comment]
Returns -1 and not 130

**Comment by Chr-ss** [comment]
Same with other signals

**Comment by Chr-ss** [comment]
![IMG_20240802_115954](https://github.com/user-attachments/assets/e5a230ff-4a4b-4a4e-bf86-4861afc64010)

**Comment by Chr-ss** [comment]
![IMG_20240802_120247](https://github.com/user-attachments/assets/01b43676-989f-448c-976c-e4951bb67219)


This should be it!

**Comment by sairutra** [comment]
fixed in 5f0e374fe8d4482dd0a154da29cd1338cc352170
