### ISSUE TITLE
./dir should print "./dir is a directory" see photo

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#114]

**Comment by Chr-ss** [comment]
![IMG_20240802_130021](https://github.com/user-attachments/assets/4401b49c-cd59-4e59-926e-d45f66070fc4)
![IMG_20240802_130023](https://github.com/user-attachments/assets/f776793a-6146-429d-8ec5-688af92bf787)
![IMG_20240802_130026](https://github.com/user-attachments/assets/7105abc7-6b5a-43a7-89ba-a0cab7478ae8)

**Comment by sairutra** [comment]
fix in f48c8596f84c241f30ad5e862f1751df80365ff6

but do double check @Chr-ss
