### ISSUE TITLE
CTRL + / in heredoc

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#126]

**Comment by sairutra** [comment]
There needs to be a clear heredoc function to clear the heredoc if signal is received to make this work properly 
minishell:~$ cat << EOF
>
>
>asb
>
>^C
nl
nl
asb
nl

doing signal interrupt will still take everything from heredoc readline to execution, while this should not happen

**Comment by sairutra** [comment]
fixed in 08223150fe56d0f050a288d2648832c35b609d9b
