### ISSUE TITLE
cd -> pwd envp should be absolute path, not relative

### ISSUE THREAD

**Issue by sairutra** [Chr-ss/minishell#59]

**Comment by Chr-ss** [comment]
minishell:~$pwd
/home/crasche/github/minishell/src
minishell:~$cd ..
minishell:~$pwd
/home/crasche/github/minishell
minishell:~$cd ./src/
minishell:~$pwd
/home/crasche/github/minishell/src
minishell:~$env
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
LANGUAGE=en
LC_TIME=nl_NL.UTF-8
USER=crasche
XDG_SESSION_TYPE=x11
SHLVL=1
HOME=/home/crasche
DESKTOP_SESSION=ubuntu
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/code.desktop
GTK_MODULES=gail:atk-bridge
FEH_PID=55081
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
LC_CTYPE=en_US.UTF-8
LC_MONETARY=nl_NL.UTF-8
MANAGERPID=55023
SYSTEMD_EXEC_PID=55694
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/154522/bus
LIBVIRT_DEFAULT_URI=qemu:///system
YAD_PID=55537
GIO_LAUNCHED_DESKTOP_FILE_PID=56291
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LOGNAME=crasche
GTK_IM_MODULE=ibus
JOURNAL_STREAM=8:303673
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
XDG_SESSION_CLASS=user
FT_HOOK_PATHNAME=login-user.d
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LC_COLLATE=en_US.UTF-8
PATH=/home/crasche/bin:/home/crasche/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/crasche/.dotnet/tools
GDM_LANG=en
SESSION_MANAGER=local/f1r2s16.codam.nl:@/tmp/.ICE-unix/55676,unix/f1r2s16.codam.nl:/tmp/.ICE-unix/55676
INVOCATION_ID=cda2d113e8a64ac8b6c8d15d67382e7c
LC_ADDRESS=nl_NL.UTF-8
XDG_RUNTIME_DIR=/run/user/154522
XDG_MENU_PREFIX=gnome-
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
DISPLAY=:0
LANG=en_US.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/crasche/.cache/dotnet_bundle_extract
XDG_CURRENT_DESKTOP=Unity
XAUTHORITY=/home/crasche/.Xauthority
XDG_SESSION_DESKTOP=ubuntu
XMODIFIERS=@im=ibus
LC_MESSAGES=en_US.UTF-8
SSH_AGENT_LAUNCHER=gnome-keyring
SSH_AUTH_SOCK=/run/user/154522/keyring/ssh
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/crasche
LC_NAME=nl_NL.UTF-8
SHELL=/bin/zsh
KRB5CCNAME=FILE:/tmp/krb5cc_154522_Wpb31m
QT_ACCESSIBILITY=1
GDMSESSION=ubuntu
LC_MEASUREMENT=nl_NL.UTF-8
FT_HOOK_NAME=login-user
LC_IDENTIFICATION=nl_NL.UTF-8
GPG_AGENT_INFO=/run/user/154522/gnupg/S.gpg-agent:0:1
GJS_DEBUG_OUTPUT=stderr
QT_IM_MODULE=ibus
LC_ALL=
**PWD=./src/**
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/home/crasche/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
LC_NUMERIC=nl_NL.UTF-8
LC_PAPER=nl_NL.UTF-8
CHROME_DESKTOP=code-url-handler.desktop
ORIGINAL_XDG_CURRENT_DESKTOP=ubuntu:GNOME
GDK_BACKEND=x11
OLDPWD=..
DOCKER_HOST=unix:///run/user/154522/docker.sock
_=/home/crasche/github/minishell/./minishell
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.90.2
COLORTERM=truecolor
GIT_ASKPASS=/usr/share/code/resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/usr/share/code/code
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/usr/share/code/resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/run/user/154522/vscode-git-8bba44c7e3.sock
VSCODE_INJECTION=1
ZDOTDIR=/home/crasche
USER_ZDOTDIR=/home/crasche
TERM=xterm-256color

**Comment by sairutra** [comment]
fixed in 898b577c46bd23803cb5c1ad93922cb2fa0499b9
