### ISSUE TITLE
Tester expanding "*", even with expanding unsure why this is not matching

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#80]
16 | echo "> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<" 
mini output = (> >> < cases e2e.sh files files_temp interactive.sh logs README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)
bash output = (> >> < cases e2e.sh files files_temp interactive.sh logs README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)
17 | echo '> >> < * ? [ ] | ; [ ] || && ( ) & # $ \ <<' 
mini output = (> >> < cases e2e.sh files files_temp interactive.sh logs README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)
bash output = (> >> < cases e2e.sh files files_temp interactive.sh logs README.md util xdotool ? [ ] | ; [ ] || && ( ) & # $ \ <<)

**Comment by sairutra** [comment]
fixed in 37f1238368c9ed1ce60e6435151af9c578bd2f36, not sure how
