### ISSUE TITLE
cd leaks when not given valid path

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#81]
==37262== 
cminishell:~$cd 123132
cd
minishell:~$
==37262== 
==37262== HEAP SUMMARY:
==37262==     in use at exit: 208,189 bytes in 223 blocks
==37262==   total heap usage: 598 allocs, 375 frees, 232,974 bytes allocated
==37262== 
==37262== 9 bytes in 1 blocks are definitely lost in loss record 3 of 64
==37262==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==37262==    by 0x407FE5: ft_calloc (in /home/crasche/github/minishell/minishell)
==37262==    by 0x4075AA: ft_strjoin (in /home/crasche/github/minishell/minishell)
==37262==    by 0x404BC5: cd_parse_dso (cd_parse.c:23)
==37262==    by 0x404FF4: cd_parse (cd_parse.c:127)
==37262==    by 0x4052B0: cd (cd.c:105)
==37262==    by 0x402A5E: execute_check_builtin (execution.c:130)
==37262==    by 0x402DE2: execute (execution.c:203)
==37262==    by 0x406760: input_handling (input_handling.c:45)
==37262==    by 0x4065FD: main (main.c:25)
==37262== 
==37262== LEAK SUMMARY:
==37262==    definitely lost: 9 bytes in 1 blocks
==37262==    indirectly lost: 0 bytes in 0 blocks
==37262==      possibly lost: 0 bytes in 0 blocks
==37262==    still reachable: 0 bytes in 0 blocks
==37262==         suppressed: 208,180 bytes in 222 blocks
==37262== 
==37262== For lists of detected and suppressed errors, rerun with: -s
==37262== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by sairutra** [comment]
fixed in 791c9e6466af583fa3c86c9f1f1ef25a9d9c177d
