### ISSUE TITLE
cd error behavior

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#82]
minishell:~$cd 123123
cd
minishell:~$bash 
crasche@f1r6s10:~/github/minishell$ cd 123123
bash: cd: 123123: No such file or directory
crasche@f1r6s10:~/github/minishell$ cd $PWD hi
bash: cd: too many arguments
crasche@f1r6s10:~/github/minishell$ 
exit
minishell:~$cd $PWD hi
too many arguments
cd
minishell:~$

**Comment by sairutra** [comment]
fixed in 8bf2eaada76ba5b58f58f7c113076dba79d05bce
