### ISSUE TITLE
expand exit code leaks

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#83]
minishell:~$export 123
minishell: export: not a valid identifier
minishell:~$echo $?
0
minishell:~$
==37927== 
==37927== HEAP SUMMARY:
==37927==     in use at exit: 208,182 bytes in 223 blocks
==37927==   total heap usage: 542 allocs, 319 frees, 232,255 bytes allocated
==37927== 
==37927== 2 bytes in 1 blocks are definitely lost in loss record 1 of 64
==37927==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==37927==    by 0x407FE5: ft_calloc (in /home/crasche/github/minishell/minishell)
==37927==    by 0x407A75: ft_itoa (in /home/crasche/github/minishell/minishell)
==37927==    by 0x403675: expand_exit_code (expansion.c:19)
==37927==    by 0x403555: expand_copy (expansion.c:74)
==37927==    by 0x403408: expand (expansion.c:94)
==37927==    by 0x4066A7: input_handling (input_handling.c:29)
==37927==    by 0x4065FD: main (main.c:25)
==37927== 
==37927== LEAK SUMMARY:
==37927==    definitely lost: 2 bytes in 1 blocks
==37927==    indirectly lost: 0 bytes in 0 blocks
==37927==      possibly lost: 0 bytes in 0 blocks
==37927==    still reachable: 0 bytes in 0 blocks
==37927==         suppressed: 208,180 bytes in 222 blocks
==37927== 
==37927== For lists of detected and suppressed errors, rerun with: -s

**Comment by sairutra** [comment]
this is the same issue as [#84](https://github.com/Chr-ss/minishell/issues/84)
