### ISSUE TITLE
minishell exit unexpected: echo test < files/outfiles/doesnotexsits 

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#85]
minishell:~$echo test < files/outfiles/doesnotexsits 
test
minishell:~$==38797== 
==38797== HEAP SUMMARY:
==38797==     in use at exit: 208,180 bytes in 222 blocks
==38797==   total heap usage: 532 allocs, 310 frees, 232,329 bytes allocated
==38797== 
==38797== LEAK SUMMARY:
==38797==    definitely lost: 0 bytes in 0 blocks
==38797==    indirectly lost: 0 bytes in 0 blocks
==38797==      possibly lost: 0 bytes in 0 blocks
==38797==    still reachable: 0 bytes in 0 blocks
==38797==         suppressed: 208,180 bytes in 222 blocks
==38797== 
==38797== For lists of detected and suppressed errors, rerun with: -s
==38797== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
f1r6s10% cd ../..
f1r6s10% echo test < files/outfiles/doesnotexsits 
zsh: no such file or directory: files/outfiles/doesnotexsits
f1r6s10% ./minishell 
minishell:~$echo test < files/outfiles/doesnotexsits 
files/outfiles/doesnotexsits: Permission denied
error in parsing, cmds not executed: No such file or directory
f1r6s10%

**Comment by sairutra** [comment]
fixed in #87
