### ISSUE TITLE
cat + CTRL C 

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#92]
we are currently showing a double prompt

tycho: "I can't remember but we did some tricky stuff with signals"

**Comment by sairutra** [comment]
minishell:~$cat 
^C
minishell:~$minishell:~$

**Comment by sairutra** [comment]
fixed in [16c0981](https://github.com/Chr-ss/minishell/commit/16c0981dc1469e3263e1191e71c678b446f30501)

**Comment by Chr-ss** [comment]
cat 
CTRL + C

---

after changes in pipe branch has no new line

**Comment by sairutra** [comment]
fix again in 88fc5072b87e7a76d44c7075a4bd7e7025a937bf
