### ISSUE TITLE
CRTL + \

### ISSUE THREAD

**Issue by Chr-ss** [Chr-ss/minishell#94]
CRTL + \ should do nothing in interactive mode but if we have a hang because of "cat" or "sleep infinity" if should quit back to interactive more.

Handle ctrl-C, ctrl-D and ctrl-\ which should behave like in bash.

• In interactive mode:
◦ ctrl-C displays a new prompt on a new line.
◦ ctrl-D exits the shell.
◦ ctrl-\ does nothing.

**Comment by sairutra** [comment]
fixed in [16c0981](https://github.com/Chr-ss/minishell/commit/16c0981dc1469e3263e1191e71c678b446f30501)
